name: h2gis-custom-functions

on: [push]

jobs:
  build:
    env:
      bintrayUser: ${{secrets.bintrayUser}}
      bintrayKey: ${{secrets.bintrayKey}}
      BUILD_NUMBER: ${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build 
        run: ./gradlew clean build
      - name: Publish Jar
        if: success() && github.ref == 'refs/heads/master'
        run: ./gradlew bintrayUpload
